### ISSUE TITLE
Aditional Configuration

### ISSUE THREAD

**Issue by Skunkynator** [danielfvm/Show#8]
Add support for config files that have arguments pre specified and can point to textures/3D models to also load and draw.

- [ ] Add argument to point to config file
- [ ] Parse config file
- [ ] Support loading images and give them to the shader
- [ ] Support loading 3D models and draw them in front of the main rect
- [ ] Support specifying different shaders for the 3D models

**Comment by Skunkynator** [comment]
If this issue gets accepted, I'd like to implement the config file argument and parsing.
I am also up to implement other parts if no one else wants to.

**Comment by danielfvm** [comment]
How would loading a model from the config file look like? Whats the structure? How would you specify which shaders belong to which model and what about coordinates, scale the model has? Could you maybe make a small mockup config? Otherwise feel free to implement it.

I also thought about having the ability to set an image in the background instead or behind the shader.

**Comment by Skunkynator** [comment]
Here is a small mockup config using the toml format:
```toml
[arguments]
speed = 1.2
quality = 0.8 #maybe allow  values higher then 1 for anti aliasing
mode = "root"
opacity = 0.9 #not used in root mode

[fragment]
path = "./relative/to/the/conf/file.fragment"

[[fragment.textures]]
name = "const_var_name"
path = "path/to/image.png"

[[fragment.textures]]
name = "another_img"
path = "yep.png"

[[models]]
path = "/path/can/also/be/absolute.obj"
vertex_path = "shader.vert"
fragment_path = "shader.frag" #if not specified, use fallback shader for either
position = [1.5, 0, -13.2] # "camera" points towards -Z by default
perspective = true #specifies if using perspective or orthographic projection

[[models.textures]]
# same format as fragment.textures

[[global_textures]]
#same as fragment.textures but given to every shader
```

**Comment by danielfvm** [comment]
What about multiple monitors and multiple models?

**Comment by Skunkynator** [comment]
okay, i have an idea for that now, we remove the arguments section of the above example and instead add a second file with this format:
```toml
[[Instances]]
speed = 1
quality = 0.5
mode = "window"
opacity = 0.5
displays = ["DP-2","DP-1"]
wallpaper = "wallpaper.conf"

[[Instances]]
displays = ["HDMI-1"]
wallpaper = "examples/wallpaper.conf"
```
so the first example file is more for the effect creators, whereas the second is more for the ones using the effects
